AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Stack to test integration between API Gateway and Lambda to invoke an specific version.


Parameters:
  Environment:
    Type: String
    Default: staging
    Description: Environment Name

Resources:
##########################################################################
# User Role
##########################################################################
  TestApiGatewayLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: tests.role.lambda.TestApiGatewayLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess

##########################################################################
# Lambda Function
##########################################################################
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: main.lambda_handler
      Runtime: python3.10
      Role: !GetAtt TestApiGatewayLambdaRole.Arn
      Timeout: 300
      MemorySize: 512
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENVIRONMENT_NAME: !Ref Environment
      AutoPublishAlias: dev
      Events:
        APIFunction:
          Type: Api
          Properties:
            Path: /my_endpoint
            Method: post
            RestApiId:
              Ref: TestApi

##########################################################################
# Lambda Aliases

## Remove comments in the second deploy

##########################################################################
  # V202308Alias:
  #   Type: AWS::Lambda::Alias
  #   Properties:
  #     FunctionName: !Ref TestFunction
  #     FunctionVersion: "2"
  #     Name: v_2023_08

##########################################################################
# REST API
##########################################################################
  TestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: test-apigw-lambda-stages
      Description: REST API demo to test Stages

##########################################################################
# REST API Resources
##########################################################################
  TestApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TestApi
      ParentId: !GetAtt [TestApi, RootResourceId]
      PathPart: my_endpoint  # match with the path in Lambda Events

##########################################################################
# REST API Method
##########################################################################
  RootMethodPOST:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref TestApi
      ResourceId: !Ref TestApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: False
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join: 
            - ''
            - - 'arn:aws:apigateway:'
              - !Ref 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - !GetAtt TestFunction.Arn
              - ':${stageVariables.lambdaAlias}/invocations'

##########################################################################
# REST API Resources to version: dev
# stage and deployment + Lambda::Permission
##########################################################################
  DeploymentDev:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - RootMethodPOST
    Properties:
      RestApiId: !Ref TestApi
      Description: 'Deployment for Dev Alias'

  StageDev:  
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: dev
      RestApiId: !Ref TestApi
      DeploymentId: !Ref DeploymentDev
      Variables: 
        lambdaAlias: dev # match with the Lambda Alias
  
  LambdaInvokePermissionDev:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::Join: 
          - ''
          - - !GetAtt TestFunction.Arn
            - ':dev' # match with the Lambda Alias
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: 
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TestApi}/dev/POST/my_endpoint

##########################################################################
# REST API Resources to version: v_2023_08
# stage and deployment + Lambda::Permission
##########################################################################
  DeploymentV202308:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - RootMethodPOST
    Properties:
      RestApiId: !Ref TestApi
      Description: 'Deployment for v_2023_08 Alias'

  StageV202308:  
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: v_2023_08
      RestApiId: !Ref TestApi
      DeploymentId: !Ref DeploymentV202308
      Variables: 
        lambdaAlias: v_2023_08 # match with the Lambda Alias

  LambdaInvokePermissionV202308:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::Join: 
          - ''
          - - !GetAtt TestFunction.Arn
            - ':v_2023_08' # match with the Lambda Alias
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: 
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TestApi}/v_2023_08/POST/my_endpoint
